using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Spawner : MonoBehaviour
{
    //public Note note;
    public Note[] notes = new Note[20];
    public Vector3 startPos;            // ì²˜ìŒ ?œì‘ ??spawner position
    public Vector3 currPos;             // update?˜ëŠ” spawner??random position

    public Transform hitTrans;
    public Transform playerTrans;
    public Transform noteParent;        // ?ï¿½ì´?ï¿½ë¼?ï¿½ì°½??clone??note?ï¿½ì„ ê´€ë¦¬í•˜??parent

    private bool canShoot;

    void Start()
    {
        startPos = transform.localPosition;     // 0, 6, 20 ê³ ì •
        canShoot = true;
    }

    void Update()
    {
        if (canShoot)
        {
            StartCoroutine(ShootNote());
        }
    }

    IEnumerator ShootNote()
    {
        canShoot = false;
        currPos = startPos + new Vector3(Random.Range(-5f, 5f), Random.Range(-3f, 3f), 0f);
        int noteIdx = Random.Range(0, notes.Length);

        Note noteTemp = Instantiate(notes[noteIdx], noteParent);
        noteTemp.Init(currPos, hitTrans.localPosition, playerTrans.eulerAngles);

        yield return new WaitForSeconds(1.0f);      // 1ì´ˆë§ˆ???ï¿½ì„±
        canShoot = true;
    }
}